config/routes.rb
QloudShare::Application.routes.draw do
  
  resources :fronts

  resources :users
  resources :user_sessions
  resources :static_pages
  resources :plans
  resources :user_plans
  resources :features
  resources :contacts
  resources :folders
  
  get 'logout' => 'user_sessions#destroy', :as => :logout
  get 'login' => 'user_sessions#new', :as => :login
  match 'signup' => 'user_sessions#signup', :as => :signup, via: [:get, :post, :patch]
  
  match 'dashboard' => 'fronts#dashboard', :as => :dashboard, via: [:get, :post, :patch]
  get '/other/:page_id' => 'fronts#other', :as => :other
  
  match '/forgot_password' => 'fronts#forgot_password', :as => :forgot_password, via: [:get, :post]
  match '/change_password' => 'fronts#change_password', :as => :change_password, via: [:get, :post, :patch]
  match '/profile' => 'fronts#profile', :as => :profile, via: [:get, :post, :patch]
  get 'usage' => 'fronts#usage', :as => :usage
  match 'contact_us' => 'fronts#contact_us', :as => :contact_us, via: [:get, :post, :patch]
  match 'help' => 'fronts#help', :as => :help, via: [:get, :post, :patch]
  get '/download/:id' => 'fronts#download', :as => :download
  
  get '/sub_folders/:parent_folder_id' => 'folders#sub_folders', :as => :sub_folders
  
  get '/show_search_box/:toggle/:model/:pm' => 'fronts#show_search_box', :as => :show_search_box      
  
  root 'fronts#dashboard'

  

end

app/models/share.rb
class Share < ActiveRecord::Base
  belongs_to :user
  belongs_to :folder

  validates :shared_by, :presence => true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message: 'Invalid email address' }
end

app/controllers/shares_controller.rb
class SharesController < ApplicationController
  before_action :set_share, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction
  before_action :require_admin
  before_action :set_header_menu_active
  # GET /shares
  # GET /shares.json
  def index
    @o_all = get_records(params[:share], params[:page])
  end
  
  # GET /shares/1
  # GET /shares/1.json
  def show
  end

  # GET /shares/new
  def new
    @o_single = Share.new
  end

  # GET /shares/1/edit
  def edit
  end

  # POST /shares
  # POST /shares.json
  def create
    @o_single = Share.new(share_params)

    respond_to do |format|
      if @o_single.save        
        format.html { redirect_to shares_url, notice: t("general.successfully_created") }
        format.json { render action: 'show', status: :created, location: @o_single }
      else
        format.html { render action: 'new' }
        format.json { render json: @o_single.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shares/1
  # PATCH/PUT /shares/1.json
  def update
    respond_to do |format|
      if @o_single.update_attributes(share_params)
        format.html { redirect_to shares_url, notice: t("general.successfully_updated") }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @o_single.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shares/1
  # DELETE /shares/1.json
  def destroy
    @o_single.destroy
    respond_to do |format|
      format.html { redirect_to shares_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_share
      @o_single = Share.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def share_params
      params.require(:share).permit!
    end
    
    def get_records(search, page)
      share_query = Share.scoped
      share_query.order(sort_column + " " + sort_direction).paginate(:per_page => 10, :page => page)
    end    
    
    def set_header_menu_active
      @shares = true
    end
    
    def sort_column
      Share.column_names.include?(params[:sort]) ? params[:sort] : "id"
    end
  
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
    end       
end

app/views/shares/_fetchAll.html.erb
<table class="table table-striped">
 <thead> 
  <tr>
    <th width="30%"><%= sortable "name", t("general.name") %></th>
    <th width="30%"><%= sortable "page_route", t("general.page_route") %></th>
    <th width="20%"><%= sortable "created_at", t("general.created_at")%></th>
    <th width="10%"><%= sortable "is_footer", t("general.is_footer") %></th>
    <th width="10%"><%= t("general.actions") %></th>
  </tr>
 </thead> 
  
  <tbody>
    <% if @o_all.size > 0 %>
      <% @o_all.each do |o_row| %>
        <tr>
          <td><%= o_row.name %></td>
          <td><%= o_row.page_route %></td>
          <td><%= o_row.created_at.to_s(:pretty) %></td>
          <td><%= o_row.is_footer ? image_tag("Yes.gif") : image_tag("No.gif") %></td>
          <td> 
			      <%= link_to t('.edit', :default => t("helpers.links.edit")),
			                  edit_static_page_path(o_row), :class => 'btn btn-mini' %>
			      <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
			                  static_page_path(o_row),
			                  :method => :delete,
			                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
			                  :class => 'btn btn-mini btn-danger' %>
          </td>
        </tr>
      <% end %>
    <% else %>
      <tr><th colspan="6"><%= t("general.record_not_found") %></th></tr>
    <% end %>      
  </tbody>
</table>
<div class="fRight">
	<%= will_paginate @o_all %>
</div>	

app/views/shares/_form.html.erb
<%= form_for @o_single, :html => { :class => 'form-horizontal' } do |f| %>
	<fieldset>
		<legend></legend>
   
    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %><span class="redStart">*</span>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
       	<% if @o_single.errors[:name].any? %>
        	<span class="text-error text-message"><%= @o_single.errors[:name].first %></span>
      	<% end %>        
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :page_route, :class => 'control-label' %><span class="redStart">*</span>
      <div class="controls">
        <%= f.text_field :page_route, :class => 'text_field' %>
       	<% if @o_single.errors[:page_route].any? %>
        	<span class="text-error text-message"><%= @o_single.errors[:page_route].first %></span>
      	<% end %>                
      </div>
    </div>
    	
    <div class="control-group"><%= f.label :content, :class => 'control-label' %><div class="controls"><%= f.text_area :content, :class => 'text_field' %></div></div>
		 
    <div class="control-group">
      <%= f.label :is_footer, :class => 'control-label' %>
      <div class="controls">
        <%= f.check_box :is_footer, :class => 'check_box' %>
      </div>
    </div>			 
     
    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', users_url, :class => 'btn' %>
    </div>
    
  </fieldset>
<% end %>

app/views/shares/edit.html.erb
<%- model_class = StaticPage -%>
<div class="page-header">
  <h4><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h4>
</div>
<%= render :partial => 'form' %>

app/views/shares/index.html.erb
<%- model_class = StaticPage -%>

<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>

<div class="page-header">
  <h4><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %> (<span id="count_records"><%= @o_all.count %></span>)</h4>
</div>    

<div class="searchRight">
	
	<%= link_to t('.new', :default => t("helpers.links.new")),
	            new_static_page_path,
	            :class => 'btn btn-primary' %>
</div>	

<div id="div_update_search"></div>

<div id="div_update">
	<%= render "fetchAll" %>
</div>

app/views/shares/index.js.erb
$("#div_update").html("<%= escape_javascript(render("fetchAll")) %>");
$("#count_records").html("<%= @o_all.count %>");
$("#spinner").hide();

app/views/shares/new.html.erb
<%- model_class = StaticPage -%>
<div class="page-header">
  <h4><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h4>
</div>
<%= render :partial => 'form' %>