config/routes.rb
QloudShare::Application.routes.draw do
  
  resources :fronts

  resources :users
  resources :user_sessions
  resources :static_pages
  resources :plans
  resources :user_plans
  resources :features
  resources :contacts
  resources :folders
  
  get 'logout' => 'user_sessions#destroy', :as => :logout
  get 'login' => 'user_sessions#new', :as => :login
  match 'signup' => 'user_sessions#signup', :as => :signup, via: [:get, :post, :patch]
  
  match 'dashboard' => 'fronts#dashboard', :as => :dashboard, via: [:get, :post, :patch]
  get '/other/:page_id' => 'fronts#other', :as => :other
  
  match '/forgot_password' => 'fronts#forgot_password', :as => :forgot_password, via: [:get, :post]
  match '/change_password' => 'fronts#change_password', :as => :change_password, via: [:get, :post, :patch]
  match '/profile' => 'fronts#profile', :as => :profile, via: [:get, :post, :patch]
  get 'usage' => 'fronts#usage', :as => :usage
  match 'contact_us' => 'fronts#contact_us', :as => :contact_us, via: [:get, :post, :patch]
  match 'help' => 'fronts#help', :as => :help, via: [:get, :post, :patch]
  get '/download/:id' => 'fronts#download', :as => :download
  
  get '/sub_folders/:parent_folder_id' => 'folders#sub_folders', :as => :sub_folders
  
  get '/show_search_box/:toggle/:model/:pm' => 'fronts#show_search_box', :as => :show_search_box      
  
  root 'fronts#dashboard'

  

end

app/models/folder.rb
class Folder < ActiveRecord::Base
  belongs_to :user
  has_many :folders, class_name: "Folder", foreign_key: :folder_id, :dependent => :destroy
  belongs_to :parent_folder, class_name: "Folder", foreign_key: :folder_id
  has_many :files, class_name: "Folder", conditions: {is_folder: false}, :dependent => :destroy
  #validates :name, :presence => true  
  
  scope :parent_folders, -> {where("folder_id IS NULL")}
  
  mount_uploader :file_path, ImageUploader
  
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :set_folder, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction
  before_action :require_user
  before_action :set_header_menu_active
  # GET /folders
  # GET /folders.json
  def index
    session[:parent_folder_id] = nil
    @o_all = current_user.folders.parent_folders.order("is_folder desc")
    @o_single = Folder.new
    @folder = session[:folder_temp_id] ? (Folder.find(session[:folder_temp_id])) : nil
  end
  
  def sub_folders
    session[:parent_folder_id] = params[:parent_folder_id] if params[:parent_folder_id]
    @folder = session[:folder_temp_id] ? (Folder.find(session[:folder_temp_id])) : nil
    @o_single = Folder.new
    
    if session[:parent_folder_id]
      @o_folder = Folder.find(params[:parent_folder_id])
      if @o_folder.parent_folder.nil?
        @o_all = @o_folder.folders
      else
        @o_all = @o_folder.folders
      end  
    else
      @o_all = current_user.folders.parent_folders
    end
    
    @folder_tree = []
    if session[:parent_folder_id]
      fld = Folder.find(session[:parent_folder_id])
      @folder_tree << fld.name
      while fld.folder_id
        @folder_tree << fld.name
        fld = Folder.find(fld.folder_id)
      end
    end
    
    render action: 'index'
  end
  
  # GET /folders/1
  # GET /folders/1.json
  def show
  end

  # GET /folders/new
  def new
    @o_single = Folder.new
  end

  # GET /folders/1/edit
  def edit
  end

  # POST /folders
  # POST /folders.json
  def create
    @o_single = Folder.new(folder_params)     
    respond_to do |format|
      if @o_single.save
        notice = t("general.successfully_created")
        if params[:folder] and params[:folder][:file_path]
          @o_single.file_size = @o_single.file_path.size.to_f          
          @o_single.file_content_type = params[:folder][:file_path].content_type
          @o_single.name = @o_single.file_path.filename
          @o_single.is_folder = false
          @o_single.save
          #set usage
          current_user.set_total_usage(@o_single.file_size)
          session[:folder_temp_id] = @o_single.id
          notice = t("general.successfully_saved_on_cloud")
        end
        
        r_url = session[:parent_folder_id] ? sub_folders_url(session[:parent_folder_id]) : folders_url
        format.html { redirect_to r_url, notice: notice }
        format.json { render action: 'show', status: :created, location: @o_single }
      else
        format.html { render action: 'new' }
        format.json { render json: @o_single.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /folders/1
  # PATCH/PUT /folders/1.json
  def update
    respond_to do |format|
      if @o_single.update_attributes(folder_params)
        r_url = session[:parent_folder_id] ? sub_folders_url(session[:parent_folder_id]) : folders_url
        format.html { redirect_to r_url, notice: t("general.successfully_updated") }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @o_single.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /folders/1
  # DELETE /folders/1.json
  def destroy
    @o_single.destroy
    respond_to do |format|
      r_url = session[:parent_folder_id] ? sub_folders_url(session[:parent_folder_id]) : folders_url
      format.html { redirect_to r_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_folder
      @o_single = Folder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def folder_params
      params.require(:folder).permit!
    end
    
    def get_records(search, page)
      folder_query = current_user.folders.scoped
      folder_query.order(sort_column + " " + sort_direction).paginate(:per_page => 10, :page => page)
    end    
    
    def set_header_menu_active
      @folders = true
    end
    
    def sort_column
      Folder.column_names.include?(params[:sort]) ? params[:sort] : "id"
    end
  
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
    end       
end

app/views/folders/_fetchAll.html.erb
<div class="leftBlock marginRight">
	<%= form_for @o_single, :html => { :class => 'attachmentsUpload' } do |f| %>
		<table>
			<tr>
				<td>
					<h2>Locate File</h2>
			    <%= f.hidden_field :folder_id, :value => (session[:parent_folder_id] ? session[:parent_folder_id] : nil) %>
			    <%= f.hidden_field :user_id, :value => current_user.id %>
			    <%= f.file_field :file_path, :class => 'text_field' %>
			 	</td>
			 	<td>&nbsp;&nbsp;</td>   
		    <td>
					<div class="socialBlock">		
			    	<div class="socialBlockCloud">
			    		<%= link_to image_tag("cloud.png", :width => "91", :height => "91"), "#", :id => "save_on_cloud"%>
			    	</div>
			    </div>
			  </td>  
			 </tr>  
		</table>    	
	<% end %>
	
	<div class="clearBoth">&nbsp;</div>
	    
	<% if @folder %>
		<% if @folder.file_content_type.include? 'image' %>
			<%= image_tag @folder.file_path, :width => "150", :height => "" %><br />
		<% else %>
			<%= @folder.name %><br />
		<% end %>
	<% end %>	
	
	<% if session[:folder_temp_id] %>
	  <div class="socialBlock">
	  	<div class="socialBlockIcons">
	  	  <h3>How would you like to share?</h3>
	  	  	<%= link_to (image_tag "msg_icon.png", :width => "37", :height => "37", :class => "marginRight30"), "#" %>
	  	  	<%= link_to (image_tag "twitter_icon.png", :width => "37", :height => "37", :class => "marginRight30"), "#" %>
	  	  	<%= link_to (image_tag "pintrest_icon.png", :width => "37", :height => "37", :class => "marginRight30"), "#" %>
	  	  	<%= link_to (image_tag "facebook_icon.png", :width => "37", :height => "37", :class => "marginRight30"), "#" %>
	  	</div>
	  	<div class="clearBoth"></div>
	  </div>
	<% end %>  		
</div>


<div class="rightBlock width50">
	<div class="profielView">
	<% if @folder_tree %>
		<%= image_tag("design_folder.png", :width => "22", :height => "17") %>&nbsp;&nbsp;<%= @folder_tree.join(" -> ") %>
	<% end %>
  <table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
      <td width="45%" class="darkBorder"><span>Name<%= link_to image_tag("add_folder.png", :width => "22"), "#", :class => 'titleIconImg', :id => "folder_new" %></span></td>
      <td width="20%" class="darkBorder"><span><%= t("general.type") %></span></td>
      <td width="20%" class="darkBorder"><span><%= t("general.date_modified")%></span></td>
      <td width="15%" class="darkBorder"><span><%= t("general.actions")%></span></td>
    </tr>
    <% if session[:parent_folder_id] %>
    	<% if @o_folder.parent_folder.nil? %>
    		<tr><td><%= link_to "..", folders_path %></td></tr>
    	<% else %>
    		<tr><td><%= link_to "..", sub_folders_path(@o_folder.parent_folder.id) %></td></tr>
    	<% end %>	
    <% end %>
    
    <% @o_all.each do |o_row| %>
      <tr>
        <td>
        	<% if o_row.is_folder %>
        		<%= link_to image_tag("design_folder.png", :width => "22", :height => "17"), sub_folders_path(o_row.id) %>&nbsp;&nbsp;<%= o_row.name %>
        	<% else %>
        		<%= link_to o_row.name, download_path(o_row.id) %>
        	<% end %>	
        </td>
        <td><%= o_row.file_content_type %></td>
        <td><%= o_row.updated_at.to_s(:pretty) %></td>
        <td>
		      <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
		                  folder_path(o_row),
		                  :method => :delete,
		                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
		                  :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </table>
  </div>
</div>	
	
<div id="myModal" class="reveal-modal">
	<%= render 'form' %>
</div>

<script>
	$(function() {
		
		$("#folder_new").click(function () {
			$('#myModal').reveal();
		});			
		
		$("#save_on_cloud").click(function () {
			if ($("#folder_file_path").val() == "") {
				alert("Please choose file");
				return;
			}else {
				$('#spinner').show();
				$('.attachmentsUpload').submit();
			}
		});
		
		$("#save_new").click(function () {
			if ($("#folder_name").val() == "") {
				alert("Please enter name");
			}else {
				$('.save_form_new').submit();
			}
		});		
		
	});	
</script>

app/views/folders/_form.html.erb
<div class="popupBox">
	<h2>Create Folder</h2>
	<%= form_for @o_single, :html => { :class => 'save_form_new' } do |f| %>
  	<div class="inputLabel">
	    <label>Name</label>
	    <%= f.text_field :name, :class => 'text_field' %>
		  <%= f.hidden_field :file_content_type, :value => "Folder" %>
		  <%= f.hidden_field :user_id, :value => current_user.id %>
		  
		  <%= f.hidden_field :folder_id, :value => (session[:parent_folder_id] ? session[:parent_folder_id] : nil) %>	    
	    <div class="clearBoth"></div>
    </div>

    <div class="inputLabel">
      <label>&nbsp;</label>
      <%= link_to 'Create Folder', "#", :id => "save_new", :class => "btn btn-primary" %>
      <div class="clearBoth"></div>
    </div>
    <div class="clearBoth"></div>
  <% end %>  
</div>
<div class="clearBoth"></div>

app/views/folders/_share.html.erb
<div class="fb-root" id="fb-root"></div>
	<table class="table table-condensed" width="100%">
		
		
		<tr>
			<td width="100%" colspan="3">
				<!-- facebook -->
				
				<a id="shareonfacebook"> <%= image_tag "facebook.jpeg", :width => "60px" %></a>
			  <span id="spinner" style="display: none;">
			    <%= image_tag "loading.gif" %>
			  </span>  		
			</td>
		</tr>	
		
		<tr>
			<td width="100%" colspan="3">
				<!-- twitter -->
					
					<a onclick="Share.twitter('http://<%= session[:user_url] %>','')"><%= image_tag "twitter.png", :width => "60px" %></a>
			</td>	
		</tr>

	</table> 
	


<script type="text/javascript">

	$(document).ready(function () {
		Share = {
			facebook: function(purl, ptitle, pimg, text) {
				url = 'http://www.facebook.com/sharer.php?s=100';
				url += '&p[title]=' + encodeURIComponent(ptitle);
				url += '&p[summary]=' + encodeURIComponent(text);
				url += '&p[url]=' + $('#uf').attr('src');
				url += '&p[images][0]=' + encodeURIComponent(pimg);
				Share.popup(url);
			},
			
			
			twitter: function(purl, ptitle) {
				url = 'http://twitter.com/share?';
				url += 'text=' + encodeURIComponent(ptitle);
				url += '&url=' + encodeURIComponent(purl);
				url += '&counturl=' + encodeURIComponent(purl);
				Share.popup(url);
			},
			
			google: function(purl) {
				url = 'https://plus.google.com/share?&hl=en';
				url += '&url=' + encodeURIComponent(purl);
				Share.popup(url);
			},	
			
			
			popup: function(url) {
				window.open(url,'','toolbar=0,status=0,width=626, height=436');
			}
		};
	
		FB.init({
			appId : '<%= FACEBOOK_CONSUMER_KEY %>'
		});
	});
    $(document).ready(function () {
      $('#shareonfacebook').click(function (e) {
          e.preventDefault();
          FB.ui(
              {
                  method: 'feed',
									name: '',
									link: '<%= session[:user_url] %>',
									picture: '',
									description: '',
                  message: ''
              }, function(response) {
								    if (response.post_id) {
								      $.ajax({
								        type: 'GET',
								        dataType: 'json',
								        data: {"access_token": "<%= session[:token] %>"},
								        url: "https://graph.facebook.com/" + response.post_id,
								        success: function(responseData) {
								        	$("#spinner").show();
											      $.ajax({
											        type: 'GET',
											        dataType: 'json',
											        data: {"post_id": response.post_id, "content": responseData.message},
											        url: "/facebook/add_post_id",
											        success: function(responseData) {
											        	alert("Content has been shared successfully on facebook");
											        	$("#spinner").hide();
											        }
											     });
								        	//alert(JSON.stringify(responseData, null, "\t"));
								        }
								     });
								    }
								});
      });
            
  	});
</script>

app/views/folders/edit.html.erb
<%- model_class = Folder -%>
<div class="page-header">
  <h4><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h4>
</div>
<%= render :partial => 'form' %>

app/views/folders/index.html.erb
<div id="div_update">
	<%= render "fetchAll" %>
</div>

app/views/folders/index.js.erb
$("#div_update").html("<%= escape_javascript(render("fetchAll")) %>");
$("#count_records").html("<%= @o_all.count %>");
$("#spinner").hide();

app/views/folders/new.html.erb
<%- model_class = Folder -%>
<div class="page-header">
  <h4><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h4>
</div>
<%= render :partial => 'form' %>