config/routes.rb
QloudShare::Application.routes.draw do
  
  resources :fronts

  resources :users
  resources :user_sessions
  resources :static_pages
  resources :plans
  resources :user_plans
  resources :features
  resources :contacts
  resources :folders
  
  get 'logout' => 'user_sessions#destroy', :as => :logout
  get 'login' => 'user_sessions#new', :as => :login
  match 'signup' => 'user_sessions#signup', :as => :signup, via: [:get, :post, :patch]
  
  match 'dashboard' => 'fronts#dashboard', :as => :dashboard, via: [:get, :post, :patch]
  get '/other/:page_id' => 'fronts#other', :as => :other
  
  match '/forgot_password' => 'fronts#forgot_password', :as => :forgot_password, via: [:get, :post]
  match '/change_password' => 'fronts#change_password', :as => :change_password, via: [:get, :post, :patch]
  match '/profile' => 'fronts#profile', :as => :profile, via: [:get, :post, :patch]
  get 'usage' => 'fronts#usage', :as => :usage
  match 'contact_us' => 'fronts#contact_us', :as => :contact_us, via: [:get, :post, :patch]
  match 'help' => 'fronts#help', :as => :help, via: [:get, :post, :patch]
  get '/download/:id' => 'fronts#download', :as => :download
  
  get '/sub_folders/:parent_folder_id' => 'folders#sub_folders', :as => :sub_folders
  
  get '/show_search_box/:toggle/:model/:pm' => 'fronts#show_search_box', :as => :show_search_box      
  
  root 'fronts#dashboard'

  

end

app/controllers/fronts_controller.rb
class FrontsController < ApplicationController
	require 'builder'
	require 'open-uri'
  before_filter :require_user, :only => [:change_password, :download, :usage, :profile]
  before_filter :set_header_menu_active
  skip_before_filter :verify_authenticity_token, :only => [:dashboard]
  
  #dashboard
  def dashboard
    redirect_to folders_url if current_user
    
    @o_single = Folder.new
    @user_session = UserSession.new
    @o_user = User.new
    @folder = session[:folder_temp_id] ? (Folder.find(session[:folder_temp_id])) : nil
    
  	if request.post?
  	  @o_single = Folder.new(folder_params)
      if params[:folder] and params[:folder][:file_path] and @o_single.save
        if @o_single.file_path
          folder_attr = {file_size: @o_single.file_path.size.to_f,
                         file_content_type: params[:folder][:file_path].content_type,
                         name: @o_single.file_path.filename,
                         is_folder: false}
          @o_single.update_attributes(folder_attr)
          session[:folder_temp_id] = @o_single.id
        else
          flash[:error] = t("general.file_not_saved")
        end
      end
    end
  end  
  
  def show_search_box
    @o_single = params[:model].constantize.new
    @params_arr = params[:pm].split(',')
  end  
  
  
  def usage
    
  end
  
  def download
    file = Folder.find(params[:id])
    if file and file.file_path
      data = open(file.file_path.to_s)
      send_data  data.read,
                  :filename => file.name,
                  :type => "application/force-download",
                  :disposition => 'attachment'
    else
      flash[:notice] = t("general.file_does_not_exist")
      redirect_to folders_path              
    end                  
  end
  
  #forgot password
  def forgot_password
    @user = User.new
    if params[:user]
      if user = authenticate_email(params[:user][:email])
        new_pass = SecureRandom.hex(5)
        user.password = user.password_confirmation = new_pass
        user.save
        
        #options
        opts = { :username => user.name, :new_pass => new_pass }    
        
        #subject
        subject = t("general.reset_password")
        
        #send mail
        UserMailer.forgot_password_confirmation(user.email, subject, opts).deliver        
        
        @user_session = UserSession.find
        if @user_session
          @user_session.destroy
        end
        session[:user_id] = nil
        flash[:notice] = t("general.password_has_been_sent_to_your_email_address")
        redirect_to root_path 
      else
        flash[:forgot_pass_error] = t("general.no_user_exists_for_provided_email_address")
        redirect_to :action => "forgot_password"
      end
    end 
  end

  #change password
  def change_password
    @o_single = User.find(current_user.id)
    if params[:user]
      @o_single.password = params[:user][:password]
      @o_single.password_confirmation = params[:user][:password_confirmation]
      @o_single.password_required = true
      respond_to do |format|
        if @o_single.update_attributes(user_params)
          format.html { redirect_to users_url, notice: t("general.password_successfully_updated") }
          format.json { head :no_content }
        else
          format.html { render action: 'change_password' }
          format.json { render json: @o_single.errors, status: :unprocessable_entity }
        end
      end
    end  
  end
  
  #profile
  def profile
    @o_single = User.find(current_user.id)
    if params[:user]    
      respond_to do |format|
        if @o_single.update_attributes(user_params)
          format.html { redirect_to profile_url, notice: t("general.successfully_updated") }
          format.json { head :no_content }
        else
          format.html { render action: 'profile' }
          format.json { render json: @o_single.errors, status: :unprocessable_entity }
        end
      end      
    end
  end  
  
  #contact_us
  def contact_us
    if params[:contact]
      respond_to do |format|
        @o_single = Contact.new(contact_params)
        if @o_single.save
          format.html { redirect_to contact_us_url, notice: t("general.successfully_sent_inquiry") }
          format.json { head :no_content }
        else
          format.html { render action: 'contact_us' }
          format.json { render json: @o_single.errors, status: :unprocessable_entity }
        end
      end
    else
      @o_single = Contact.new        
    end
  end
  
  #help
  def help
    @o_help_content = StaticPage.find_by(page_route: "help")
    if params[:contact]
      respond_to do |format|
        @o_single = Contact.new(contact_params)
        if @o_single.save
          format.html { redirect_to help_url, notice: t("general.successfully_sent_inquiry") }
          format.json { head :no_content }
        else
          format.html { render action: 'help' }
          format.json { render json: @o_single.errors, status: :unprocessable_entity }
        end
      end
    else
      @o_single = Contact.new
    end
  end      
  
	#footer and other static pages
  def other
  	@o_single = StaticPage.where(page_route: params[:page_id]).first
  end
  

	private
 	
  def set_header_menu_active
    @dashboard = true
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit!
  end
  
  def contact_params
    params.require(:contact).permit!
  end
  
  def folder_params
    params.require(:folder).permit!
  end  
  
end

app/views/fronts/_admin_dashboard.html.erb
<%= t("general.welcome")%> <%= current_user.username %> 

app/views/fronts/_forgot_password_mail.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title></title>
<style type="text/css">
a { text-decoration:underline; color:#414141; }
a:hover { text-decoration:none; color:#a52023; }
</style>
</head>

<body style="margin:0; padding:0; font-family:Arial, Helvetica, sans-serif; font-size:13px; color:#414141px; line-height:18px; ">
	<table width="800" border="0" align="center" cellpadding="0" cellspacing="0" style="background:#f3f3f3; border:#83b1be solid 1px; border-top:none;">
  <tr>
    <td valign="top" style="padding:15px;"><table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td height="15" valign="top"></td>
      </tr>
      <tr>
        <td valign="top"> 
			<strong><%= t("general.dear") %> <%= username %>,</strong>
		</td>
      </tr>
      <tr>
        <td valign="top">&nbsp;</td>
      </tr>
      <tr>
        <td align="center" valign="top" style=" color:#be3427; font-weight:bold; font-size:15px; border:#414141 dashed 1px; text-transform:uppercase; padding:10px 0;">
		 <%= t("general.your_password_has_been_reset_successfully") %>
	 	</td>
      </tr>
      <tr>
        <td valign="top">&nbsp;</td>
      </tr>
      <tr>
        <td valign="top" style="color:#5a5a5a; line-height:22px;"> 
			<%= t("general.your_new_password_is") %>: <%= new_pass %><br />
		</td>
      </tr>
      <tr>
        <td valign="top">&nbsp;</td>
      </tr>
      <tr>
        <td valign="top">&nbsp;</td>
      </tr>
      <tr>
        <td valign="top"><%= t("general.thank_you") %><br />
          <%= t("general.web_team") %></td>
      </tr>
      
    </table></td>
  </tr>
</table>

</body>
</html>

app/views/fronts/_mainpitch.html.erb

  <table border=0 width="100%" class="table dashboard">  
    <tr valign="top">
      <td align=left valign=top width="50%">
        <h4><%= t("general.take_control_of_your_cv") %></h4>
        <p>&nbsp;</p>
        <p class="padLeft30"># <%= t("general.import_your_linkedin_profile") %></p>        
        <p class="padLeft30"># <%= t("general.try_out_various_cv_templates") %></p>
        <p class="padLeft30"># <%= t("general.control_who_see_it") %></p>
        <p class="padLeft30"># <%= t("general.vine_your_interview_answers") %></p>
        <span><%= link_to t("general.view_all_features"), "features", :class => "" %></span>    
      </td>
      
      <td align="left" valign="" width="50%">
        <iframe width="420" height="315" src="//www.youtube.com/embed/AyPzM5WK8ys" frameborder="0" allowfullscreen></iframe>
      </td>
    </tr>
  </table>

app/views/fronts/_search.html.erb
<script type="text/javascript">
	$(document).ready(function() {
	  $('.btn').click (function() {
	    $("#spinner").show();
	  });
	});
</script>
<%= form_for @o_single, :method => "get", :remote => true, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend></legend>
 
 		<% @params_arr.each do |p| %>
	    <div class="control-group">
	      <%= f.label p.capitalize, :class => 'control-label' %>
	      <div class="controls">
	      	<% model_name = params[:model].downcase %>
	        <%= f.text_field p, :value => "", :class => 'text_field' %>
	      </div>
	    </div>
  	<% end %> 
   
    <div class="controls">
      <%= f.submit t("general.search"), :class => 'btn btn-primary', :id => 'search_button_id' %>
      <input type="reset" value="<%= t("general.reset") %>" class="btn btn-primary"/>
      <span data-no-turbolink><%= link_to 'Cancel', show_search_box_path(false, params[:model], true), :class => 'btn', :remote => true %></span>
    </div>
    
  </fieldset>
     
<% end %>

app/views/fronts/_signin_form.html.erb
<div class="popupBox">
	<h2>Please sign in!</h2>
	<%= form_for @user_session, :html => { :class => 'form-horizontal' } do |f| %>
  	<div class="inputLabel">
	    <label>Email ID</label>
	    <%= f.text_field :email, :class => 'text_field' %>
	    <div class="clearBoth"></div>
    </div>
    <div class="inputLabel">
	    <label>Password</label>
	    <%= f.password_field :password, :class => 'text_field' %>
	    <div class="clearBoth"></div>
    </div>
    <div class="inputLabel">
      <%= f.submit "Sign In" %>
    </div>
  <% end %>  
  <h2>Create a Free Account!</h2>
  <%= form_for @o_user, :html => { :class => 'form-horizontal' } do |f| %>
    <div class="inputLabel">
	    <label>First Name</label>
	    <%= f.text_field :first_name, :class => 'text_field' %>
    </div>
    <div class="inputLabel">
	    <label>Email ID</label>
	    <%= f.text_field :email, :class => 'text_field' %>
    </div>
    <div class="inputLabel">
	    <label>Password</label>
	    <%= f.password_field :password, :class => 'text_field' %>
    </div>
    <div class="inputLabel">
      <%= f.submit 'Register' %>
    </div>
  <% end %>  
  
  <div class="clearBoth"></div>
</div>

app/views/fronts/change_password.html.erb
<%= form_for @o_single, :url => change_password_path, :html => { :class => 'form-horizontal' } do |f| %>
<div class="loginfom">
  <fieldset>
    <legend></legend>

	    <div class="control-group">
	    	<div class="controls">
	    		<h4><%= t("general.change_password") %></h4>
		    </div>	  
	    </div> 

    <div class="control-group">
      <%= f.label :password, :class => 'control-label' %><span class="redStart">*</span>
      <div class="controls">
        <%= f.password_field :password, :class => 'text_field' %>
       	<% if @o_single.errors[:password].any? %>
        	<span class="text-error text-message"><%= @o_single.errors[:password].first %></span>
      	<% end %>        	        
      </div>
    </div>	
    
    <div class="control-group">
      <%= f.label :password_confirmation, :class => 'control-label' %><span class="redStart">*</span>
      <div class="controls">
        <%= f.password_field :password_confirmation, :class => 'text_field' %>
	     	<% if @o_single.errors[:password_confirmation].any? %>
	      	<span class="text-error text-message"><%= @o_single.errors[:password_confirmation].first %></span>
	    	<% end %>        	        
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit t("general.change_password"), :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', root_path, :class => 'btn' %>
    </div>
    
  </fieldset>
</div>     
<% end %>

app/views/fronts/contact_us.html.erb
<%= form_for @o_single, :url => contact_us_path, :html => { :class => 'form-horizontal' } do |f| %>
<div class="loginfom">
  <fieldset>
    <legend></legend>

	    <div class="control-group">
	    	<div class="controls">
	    		<h4><%= t("general.contact_us") %></h4>
		    </div>	  
	    </div> 

    <div class="control-group">
      <label class = 'control-label'><%= t("general.your_name") %></label><span class="redStart">*</span>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
       	<% if @o_single.errors[:name].any? %>
        	<span class="text-error text-message"><%= @o_single.errors[:name].first %></span>
      	<% end %>        
      </div>
    </div>
    
    <div class="control-group">
      <label class = 'control-label'><%= t("general.your_email") %></label><span class="redStart">*</span>
      <div class="controls">
        <%= f.text_field :email, :class => 'text_field' %>
       	<% if @o_single.errors[:email].any? %>
        	<span class="text-error text-message"><%= @o_single.errors[:email].first %></span>
      	<% end %>                
      </div>
    </div>
    	
    <div class="control-group">
    	<div class="controls">
    	<%= t("general.type_your_msg_here") %>
    	<div class="clearBoth"></div>    	
    	<%= f.text_area :message, :class => 'text_field textArea' %>
    	</div>
    </div>


    <div class="form-actions">
      <%= f.submit t("general.send"), :class => 'btn btn-primary' %>
    </div>
    
  </fieldset>
</div>     
<% end %>

app/views/fronts/dashboard.html.erb
<div class="leftBlock marginRight">

    <div class="control-group textColorLeft">
			<label class = 'control-label'>
				<%= image_tag("bullet1.png") %>&nbsp;&nbsp;
				<%= t("general.upload_file_you_want_to_share") %>
			</label>	      
      <div class="controls">
      </div>
    </div>
    <div class="clearBoth">&nbsp;</div>
    
    <div class="control-group textColorLeft">
			<label class = 'control-label'>
				<%= image_tag("bullet2.png") %>&nbsp;&nbsp;
				<%= t("general.choose_how_you_want_to_share_it") %>
			</label>      
      <div class="controls">
      </div>
    </div>    

		<div class="clearBoth">&nbsp;</div>
		
	<%= form_for @o_single, :url => dashboard_path, :remote => true, :method => "post", :html => { :class => 'attachmentsUpload' } do |f| %>
	
		<h2><%= t("general.simple_as_that") %></h2>
		
		<div class="clearBoth">&nbsp;</div>
	
		<%= f.file_field :file_path, :class => 'file browseBtn' %>

		<div class="clearBoth"></div>

		<% if !@o_single.file_path.blank? %>
				<%= display_file(@o_single) %>
				<div class="clearBoth">&nbsp;</div>
				
			  <div class="socialBlock">
			  	<div class="socialBlockIcons">
			  	  <h3>How would you like to share?</h3>
			  	  	<%= link_to (image_tag "msg_icon.png", :width => "37", :height => "37", :class => "marginRight30", :id => "save_on_cloud1"), "#" %>&nbsp;
			  	  	<%= link_to (image_tag "twitter_icon.png", :width => "37", :height => "37", :class => "marginRight30", :id => "save_on_cloud2"), "#" %>&nbsp;
			  	  	<%= link_to (image_tag "pintrest_icon.png", :width => "37", :height => "37", :class => "marginRight30", :id => "save_on_cloud3"), "#" %>&nbsp;
			  	  	<%= link_to (image_tag "facebook_icon.png", :width => "37", :height => "37", :class => "marginRight30", :id => "save_on_cloud4"), "#" %>&nbsp;
			  	</div>
			  	<div class="socialBlockCloud"><%= link_to image_tag("cloud.png", :width => "91", :height => "91"), "#", :id => "save_on_cloud"%></div>
			  	<div class="clearBoth"></div>
			  </div>				
				
				
				
		<% elsif @folder and @folder.file_path? %>
			<%= display_file(@folder) %>
			<div class="clearBoth">&nbsp;</div>
			
			  <div class="socialBlock">
			  	<div class="socialBlockIcons">
			  	  <h3>How would you like to share?</h3>
			  	  	<%= link_to (image_tag "msg_icon.png", :width => "37", :height => "37", :class => "marginRight30", :id => "save_on_cloud1"), "#" %>&nbsp;
			  	  	<%= link_to (image_tag "twitter_icon.png", :width => "37", :height => "37", :class => "marginRight30", :id => "save_on_cloud2"), "#" %>&nbsp;
			  	  	<%= link_to (image_tag "pintrest_icon.png", :width => "37", :height => "37", :class => "marginRight30", :id => "save_on_cloud3"), "#" %>&nbsp;
			  	  	<%= link_to (image_tag "facebook_icon.png", :width => "37", :height => "37", :class => "marginRight30", :id => "save_on_cloud4"), "#" %>&nbsp;
			  	</div>
			  	<div class="socialBlockCloud"><%= link_to image_tag("cloud.png", :width => "91", :height => "91"), "#", :id => "save_on_cloud" %></div>
			  	
			  	<div class="clearBoth"></div>
			  </div>				
		<% end %>	
	<% end %>		
	
</div>	
<div class="rightBlock width50">
	<div class="profielView">
	
	<div class="home_more_content" style="display: visible;"> 
		<div class="textColorCenter">
			<p><%= t("general.access_file_anywhere") %></p>
			<p><%= t("general.upload_edit_share_more") %></p>
		</div>
		<%= image_tag("256-bit_map.png", :width => "560", :height => "300") %>
		<div class="textColorCenter">
			<h2><%= t("general.your_files") %></h2>
			<p><%= link_to t("general.learn_more") + " " + image_tag("green-arrow.png"), "#", :id => "learn_more" %></p>
		</div>
	</div>	
	<div class="learn_more_content" style="display: none;">
		<h3><%= t("general.why_fileone") %></h3>
    <div class="control-group textColorLeft">
			<label class = 'control-label'>
				<%= image_tag("check_icon.png") %>&nbsp;&nbsp;
				<%= t("general.learn_more1") %>
			</label>
			<label class = 'control-label'>
				<%= image_tag("check_icon.png") %>&nbsp;&nbsp;
				<%= t("general.learn_more2") %>
			</label>
			<label class = 'control-label'>
				<%= image_tag("check_icon.png") %>&nbsp;&nbsp;
				<%= t("general.learn_more3") %>
			</label>	      
			<label class = 'control-label'>
				<%= image_tag("check_icon.png") %>&nbsp;&nbsp;
				<%= t("general.learn_more4") %>
			</label>	      
			<label class = 'control-label'>
				<%= image_tag("check_icon.png") %>&nbsp;&nbsp;
				<%= t("general.learn_more5") %>
			</label>	      													      
      <div class="controls">
      </div>
    </div>		
	</div>
			
</div>
</div>	


<div id="myModal" class="reveal-modal">
	<%= render 'signin_form' %>
</div>

<script>
	$(function() {
		$("#save_on_cloud, #save_on_cloud1, #save_on_cloud2, #save_on_cloud3, #save_on_cloud4").click(function () {
			$('#myModal').reveal();
		});
		
		$("#learn_more").click(function () {
			$('.home_more_content').hide();
			$('.learn_more_content').show();
		});		
		
		$(".attachmentsUpload input.file").change(function () {
		    if ($(".attachmentsUpload input.file").val() == "") {return;}
		    $('#spinner').show();
		    $('.attachmentsUpload').submit();
		});  
	});
</script>

app/views/fronts/forgot_password.html.erb
<%= form_for @user, :url => forgot_password_path, :html => { :class => 'form-horizontal' } do |f| %>
<div class="loginfom">
  <fieldset>
    <legend></legend>
    
	    <div class="control-group">
	    	<div class="controls">
	    		<h4><%= t("general.reset_password") %></h4>
		    </div>	  
	    </div>      

	    <div class="control-group">
	      <%= f.label :email, :class => 'control-label' %><span class="redStart">*</span>
	      <div class="controls">
	        <%= f.text_field :email, :class => 'text_field' %>
	        <% if flash[:forgot_pass_error] %>
	        	<span class="text-error text-message"><%= flash[:forgot_pass_error] %></span>
	    		<% end %>    
	       	<% if @user.errors[:email].any? %>
	        	<span class="text-error text-message"><%= @user.errors[:email].last %></span>
	      	<% end %>        
	      </div>
	    </div>

	    <div class="form-actions">
	      <%= f.submit t("general.reset_password"), :class => 'btn btn-primary' %>
	      <%= link_to 'Cancel', login_path, :class => 'btn' %>
	    </div>
  </fieldset>
</div>  
<% end %>

app/views/fronts/help.html.erb
<div class="leftBlock marginRight">
	<h4><%= t("general.help") %></h4>
	
    <div class="control-group">
    	<div class="controls">
    		<% if @o_help_content %>
    			<%= @o_help_content.content %>
    		<% end %>
	    </div>	  
    </div> 	
	
</div>
<div class="rightBlock width50">
	<div class="profielView">
	<%= form_for @o_single, :url => help_path, :html => { :class => 'form-horizontal' } do |f| %>
	<div class="loginfom">
	  <fieldset>
	    <legend></legend>
	
		    <div class="control-group">
		    	<div class="controls">
		    		<h4><%= t("general.got_a_question") %></h4>
			    </div>	  
		    </div> 
			
			<%= f.hidden_field :is_contact_us, :value => false %>
	    <div class="control-group">
	      <label class = 'control-label'><%= t("general.your_name") %></label><span class="redStart">*</span>
	      <div class="controls">
	        <%= f.text_field :name, :class => 'text_field' %>
	       	<% if @o_single.errors[:name].any? %>
	        	<span class="text-error text-message"><%= @o_single.errors[:name].first %></span>
	      	<% end %>        
	      </div>
	    </div>
	    
	    <div class="control-group">
	      <label class = 'control-label'><%= t("general.your_email") %></label><span class="redStart">*</span>
	      <div class="controls">
	        <%= f.text_field :email, :class => 'text_field' %>
	       	<% if @o_single.errors[:email].any? %>
	        	<span class="text-error text-message"><%= @o_single.errors[:email].first %></span>
	      	<% end %>                
	      </div>
	    </div>
	    	
	    <div class="control-group">
	    	<div class="controls">
	    	<%= t("general.type_your_msg_here") %>
	    	<div class="clearBoth"></div>    	
	    	<%= f.text_area :message, :class => 'text_field textAreaSmall' %>
	    	</div>
	    </div>
	
	
	    <div class="form-actions">
	      <%= f.submit t("general.send"), :class => 'btn btn-primary' %>
	    </div>
	    
	  </fieldset>
	</div>     
	<% end %>
</div>
</div>	

app/views/fronts/other.html.erb
<div class="loginfom">
	<fieldset>
		<legend></legend>
		<% if @o_single %>
	    <div class="control-group">
	      <div class="controls">
					<div class="page-header">
					  <h4><%= @o_single.name %></h4>
					</div>
	      </div>
	    </div>
			<%= @o_single.content.html_safe unless @o_single.content.blank? %>
		<% else %>
		  <h4><%= t("general.page_not_found") %></h4>
		<% end %>  
	</fieldset>
</div>

app/views/fronts/profile.html.erb
<%= form_for @o_single, :url => profile_path, :html => { :class => 'form-horizontal' } do |f| %>
<div class="loginfom">
	<fieldset>
		<legend></legend>
			
    <div class="control-group">
      <div class="controls">
				<div class="page-header">
				  <h4><%= t("general.profile") %></h4>
				</div>
      </div>
    </div>				
			
    <div class="control-group">
      <%= f.label :first_name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :first_name, :class => 'text_field' %>
      </div>
    </div>		
		
    <div class="control-group">
      <%= f.label :last_name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :last_name, :class => 'text_field' %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :email, :class => 'control-label' %><span class="redStart">*</span>
      <div class="controls">
        <%= f.text_field :email, :class => 'text_field' %>
       	<% if @o_single.errors[:email].any? %>
        	<span class="text-error text-message"><%= @o_single.errors[:email].first %></span>
      	<% end %>        
      </div>
    </div>

    <div class="control-group"><%= f.label :custom_signature, :class => 'control-label' %><div class="controls"><%= f.text_area :custom_signature, :class => 'text_field' %></div></div>		 
    <div class="control-group"><%= f.label :image, :class => 'control-label' %><div class="controls"><%= f.file_field :image, :class => 'text_field' %></div></div>
    <div class="control-group"><div class="controls"><% if @o_single.image? %><%= image_tag @o_single.image_url, :width => "100", :height => "100" %><% end %></div></div>
     
    <div class="form-actions">
      <%= f.submit t("general.save"), :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', root_url, :class => 'btn' %>
    </div>
    
  </fieldset>
</div>  
<% end %>

app/views/fronts/show_search_box.js.erb
$("#spinner").hide();
<% if params[:toggle] == "true" %>
	$("#div_update_search").html("<%= escape_javascript(render("search")) %>");
<% else %>	
	$("#div_update_search").html(" ");
<% end %>

app/views/fronts/usage.html.erb
  <fieldset>
    <legend></legend>
    
	    <div class="control-group">
	    	<div class="controls">
	    		<h4><%= t("general.usage") %></h4>
	    		<%= current_user.get_total_used %> <%= t("general.used") %> | <%= current_user.get_free_usage %> <%= t("general.free") %>  
		    </div>	  
	    </div>      
  </fieldset>