config/routes.rb
QloudShare::Application.routes.draw do
  
  resources :fronts

  resources :users
  resources :user_sessions
  resources :static_pages
  resources :plans
  resources :user_plans
  resources :features
  resources :contacts
  resources :folders
  
  get 'logout' => 'user_sessions#destroy', :as => :logout
  get 'login' => 'user_sessions#new', :as => :login
  match 'signup' => 'user_sessions#signup', :as => :signup, via: [:get, :post, :patch]
  
  match 'dashboard' => 'fronts#dashboard', :as => :dashboard, via: [:get, :post, :patch]
  get '/other/:page_id' => 'fronts#other', :as => :other
  
  match '/forgot_password' => 'fronts#forgot_password', :as => :forgot_password, via: [:get, :post]
  match '/change_password' => 'fronts#change_password', :as => :change_password, via: [:get, :post, :patch]
  match '/profile' => 'fronts#profile', :as => :profile, via: [:get, :post, :patch]
  get 'usage' => 'fronts#usage', :as => :usage
  match 'contact_us' => 'fronts#contact_us', :as => :contact_us, via: [:get, :post, :patch]
  match 'help' => 'fronts#help', :as => :help, via: [:get, :post, :patch]
  get '/download/:id' => 'fronts#download', :as => :download
  
  get '/sub_folders/:parent_folder_id' => 'folders#sub_folders', :as => :sub_folders
  
  get '/show_search_box/:toggle/:model/:pm' => 'fronts#show_search_box', :as => :show_search_box      
  
  root 'fronts#dashboard'

  

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  # attr_accessible :title, :body
  def to_key
     new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
  
  def persisted?
    false
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  #before_filter :require_user, :except => [:new, :create]
  # GET /user_sessions/new
  # GET /user_sessions/new.xml
  USER = "User"
  def index
		redirect_to new_user_session_path
  end
  
  def new
		@user_session = UserSession.new
		respond_to do |format|
			format.html # new.html.erb
			format.xml { render :xml => @user_session }
		end
  end

  # POST /user_sessions
  # POST /user_sessions.xml
  def create
    @user_session = UserSession.new(params[:user_session])
    respond_to do |format|
      if @user_session.save
				session[:user_id] = current_user.id
				session[:user_role] = current_user.role.role_type
				notice = t("general.login_successful")
				if session[:folder_temp_id]
				  #set user
				  folder = Folder.find(session[:folder_temp_id])
				  folder.user_id = current_user.id
				  folder.save
				  
				  #set usage
				  current_user.set_total_usage(folder.file_size)
				  
				  #save_file_on_cloud(folder)
				  notice = t("general.successfully_saved_on_cloud")
				end
				
				format.html { redirect_to(dashboard_path, :notice => notice) }
				format.xml { render :xml => @user_session, :status => :created, :location => @user_session }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @user_session.errors, :status => :unprocessable_entity }
      end
    end
  end

  def signup
    @o_single = User.new
    if request.post?
      @o_single = User.new(user_params)
      respond_to do |format|
        if @o_single.save
          @o_single.role = Role.find_by(:role_type => USER)
          opts = {:username => @o_single.name}
          UserMailer.registration_confirmation(@o_single.email, opts).deliver
          
         
          @user_session = UserSession.new
          @user_session.email = @o_single.email
          @user_session.password = params[:user][:password]
          
          if @user_session.save
            session[:user_id] = current_user.id
            session[:user_role] = current_user.role.role_type
            
            if session[:folder_temp_id]
              folder = Folder.find(session[:folder_temp_id])
              folder.user_id = current_user.id
              folder.save
            end
          end  
          format.html { redirect_to dashboard_url, notice: t("general.successfully_register") }
          format.json { render action: 'show', status: :created, location: @o_single }
        else
          format.html { render action: 'signup' }
          format.json { render json: @o_single.errors, status: :unprocessable_entity }
        end
      end
    end     
  end
  
  # DELETE /user_sessions/1
  # DELETE /user_sessions/1.xml
  def destroy
    @user_session = UserSession.find
    if @user_session
	    @user_session.destroy
	  end
		reset_session
		flash[:notice] = t("general.logout_successful")
    respond_to do |format|
      format.html { redirect_to "/" }
      format.xml { head :ok }
    end
  end
  
  private
  
  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit!
  end
  
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_form.html.erb
<%= form_for @user_session, :html => { :class => 'form-horizontal' } do |f| %>

<div class="loginfom">
  <fieldset>
  	<legend></legend>
  	
    <div class="control-group">
    	<div class="controls">
    		<h4><%= t("general.login") %></h4>
	    </div>	  
    </div>  	
	  <% if @user_session.errors.any? %>
	    <div class="control-group">
	    	<div class="controls">
	      	<% @user_session.errors.full_messages.each do |msg| %>
	      		<% @msg_var = "general.#{msg.gsub(' ', "_")}" %>
		      	<span class="text-error"><%= t(@msg_var) %></span>
		    	<% end %>
		    </div>	  
	    </div>
	  <% end %>
  	
    <div class="control-group">
      <%= f.label :email, :class => 'control-label' %><span class="redStart">*</span>
      <div class="controls">
        <%= f.text_field :email, :class => 'text_field' %>
      </div>
    </div>
 
    <div class="control-group">
      <%= f.label :password, :class => 'control-label' %><span class="redStart">*</span>
      <div class="controls">
        <%= f.password_field :password, :class => 'text_field' %>
      </div>
    </div> 
 
    <div class="form-actions">
      <%= f.submit t("general.login"), :class => 'btn btn-primary' %>
      <%= link_to t("general.click_here_to_recover_your_account"), forgot_password_path, :class => 'btn' %>
    </div>
    
  </fieldset>
</div>     
<% end %>

app/views/user_sessions/new.html.erb
<%= render 'form' %>

app/views/user_sessions/signup.html.erb
<%= form_for @o_single, :url => signup_path, :html => { :class => 'form-horizontal' } do |f| %>
<div class="loginfom">
	<fieldset>
		<legend></legend>
		
    <div class="control-group">
    	<div class="controls">
				<h4><%= t("general.sign_up") %></h4>
	    </div>	  
    </div>  			
			
    <div class="control-group">
      <%= f.label :first_name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :first_name, :class => 'text_field' %>
      </div>
    </div>		
		
    <div class="control-group">
      <%= f.label :last_name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :last_name, :class => 'text_field' %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :email, :class => 'control-label' %><span class="redStart">*</span>
      <div class="controls">
        <%= f.text_field :email, :class => 'text_field' %>
       	<% if @o_single.errors[:email].any? %>
        	<span class="text-error text-message"><%= @o_single.errors[:email].first %></span>
      	<% end %>        
      </div>
    </div>
    
   
		<% if @o_single.new_record? %>
	    <div class="control-group">
	      <%= f.label :password, :class => 'control-label' %><span class="redStart">*</span>
	      <div class="controls">
	        <%= f.password_field :password, :class => 'text_field' %>
	       	<% if @o_single.errors[:password].any? %>
	        	<span class="text-error text-message"><%= @o_single.errors[:password].first %></span>
	      	<% end %>        	        
	      </div>
	    </div>	
	    
	    <div class="control-group">
	      <%= f.label :password_confirmation, :class => 'control-label' %><span class="redStart">*</span>
	      <div class="controls">
	        <%= f.password_field :password_confirmation, :class => 'text_field' %>
		     	<% if @o_single.errors[:password_confirmation].any? %>
		      	<span class="text-error text-message"><%= @o_single.errors[:password_confirmation].first %></span>
		    	<% end %>        	        
	      </div>
	    </div>		    	
		<% end %> 

   <div class="form-actions">
      <%= f.submit 'Sign Up', :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', root_url, :class => 'btn' %>
   </div>
 </div>  
</fieldset>
<% end %>